export default {
    GET_USER_DETAILS: 'GET_USER_DETAILS',
    GET_USER_DETAILS_FETCHING: 'GET_USER_DETAILS_FETCHING',
    GET_USER_DETAILS_FETCHED: 'GET_USER_DETAILS_FETCHED',
    GET_USER_DETAILS_ERROR: 'GET_USER_DETAILS_ERROR',
    GET_EMPLOYEE_ID: 'GET_EMPLOYEE_ID'
};